# Generated by Django 5.1.7 on 2025-05-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_address_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, help_text='Введите адрес или выберите на карте', max_length=255, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Долгота'),
        ),
    ]
